# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d4da7e7971e37c9156ddd40964d8eb50622f8c57d6beb0142f302a7a3cd690987f9b0faf1d6e567776ac18bd2262286125a59740c38c19825ac02fb396a1dad

test:
  secret_key_base: da53bcd12e9e0b48358a36c42e0c02d6f4a1c32217c024d1230f39ebc8225f681979707961ad6dc3e10f964b487c8d697f865e6487b870fa369e9964ca7e12be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
